import type { Metadata, Viewport } from "next";
import localFont from "next/font/local";
import "./globals.css";
import ThemeColorSync from "./components/ThemeColorSync";

export const viewport: Viewport = {
  themeColor: "#f3f2f2",
};

const coopFont = localFont({
  src: [
    {
      path: "../public/fonts/CoopRg.ttf",
      weight: "400",
      style: "normal",
    },
    {
      path: "../public/fonts/CoopIt.ttf",
      weight: "400",
      style: "italic",
    },
    {
      path: "../public/fonts/CoopBd.ttf",
      weight: "700",
      style: "normal",
    },
    {
      path: "../public/fonts/CoopBdIt.ttf",
      weight: "700",
      style: "italic",
    },
  ],
  variable: "--font-coop",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <meta
          name="viewport"
          content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no, viewport-fit=cover"
        />
        <link
          href="https://fonts.googleapis.com/css2?family=Material+Symbols+Rounded:opsz,wght,FILL,GRAD@20,600,0,0"
          rel="stylesheet"
        />
      </head>
      <body
        className={`${coopFont.variable} font-sans antialiased`}
        style={{
          maxWidth: "390px",
          marginLeft: "auto",
          marginRight: "auto",
          minHeight: "100vh",
        }}
      >
        <ThemeColorSync />
        {children}
      </body>
    </html>
  );
}
